services:
  postgres:
    image: postgres:18
    container_name: paideia_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: paideia
      POSTGRES_PASSWORD: paideia_password
      POSTGRES_DB: paideia_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U paideia"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      paideia_net:
        ipv4_address: 172.28.0.3

  minio:
    image: minio/minio:latest
    container_name: paideia_minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: paideia_minio
      MINIO_ROOT_PASSWORD: paideia_minio_secret
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      paideia_net:
        ipv4_address: 172.28.0.4

  drizzle-gateway:
    image: ghcr.io/drizzle-team/gateway:latest
    container_name: drizzle-gateway
    restart: unless-stopped
    ports:
      - "4983:4983"
    environment:
      PORT: 4983
      STORE_PATH: ./app
      DATABASE_URL: postgresql://paideia:paideia_password@postgres:5432/paideia_db
    volumes:
      - drizzle-gateway:/app
    networks:
      paideia_net:
        ipv4_address: 172.28.0.5
    depends_on:
      - postgres

volumes:
  minio_data:
  postgres_data:
  drizzle-gateway:

networks:
  paideia_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
